### ISSUE TITLE
Does not seem to compile on most recent compiler

### ISSUE THREAD

**Issue by rivertam** [OTL/gear#5]
Hey @OTL, just a heads up in case you didn't notice the docs failed to build as well. I'm not sure when this started failing, but essentially `ncollide3d` seems to be outdated/doesn't compile on the most recent toolchain. https://github.com/sebcrozet/kiss3d/issues/167

The issue is a bit hard to escape because you use kiss3d in `urdf-viz` as well, so I guess I was wondering if you were planning on maintaining this dependency chain. I'm vaguely working on fixing it myself, so I may send a patch if I can, but I'd rather not duplicate work.

**Comment by rivertam** [comment]
I updated the whole network, as far as I can tell. It's hard to test because I was optimistic with version numbers, but when I link them all up locally, everything seems to be fine in each of them and `cargo test` works and everything.

**Comment by OTL** [comment]
Thank you for great contribution!

I'll merge and release one by one, from k, urdf-viz, then gear.

**Comment by rivertam** [comment]
Excellent. Thanks for your work on these libraries. =)
